Added method to get context from model or store and another to expand the url using a context
BlueBrain/nexus-forge pull request #315
Opened 2023-07-04 15:07 UTC by crisely09

Related to [this issue](https://bbpteam.epfl.ch/project/issues/browse/BBPP134-536).

- Added methods to get a context from a store and from a model
- Added method to extend an URI using a given context

2023-07-13 07:50 UTC, MFSY requested changes

2023-07-13 09:31 UTC, crisely09 commented on kgforge/core/forge.py
> +        self._store.mapper = DictionaryMapper(self)
this change was made

2023-07-17 08:14 UTC, crisely09 commented on kgforge/core/forge.py
> +        print("in eexpada URI")
This should be removed.

2023-07-17 08:35 UTC, MFSY commented on kgforge/core/forge.py
> +        print("in eexpada URI")
done

2023-07-17 08:35 UTC, MFSY commented on kgforge/specializations/stores/bluebrain_nexus.py
> +        return  DictionaryMapper
done

2023-07-17 08:36 UTC, MFSY approved these changes

2023-07-17 09:18 UTC, crisely09 commented
To me, it is ready to merge.

2023-07-17 13:02 UTC, merged